<?php
/*
Plugin Name: Sweet Titles
Plugin URI: http://showfom.com/sweet-titles-wordpress-plugin/
Description: Sweet Titles on your Wordpress Blog based on the Sweet Titles script by <cite><a href="http://www.dustindiaz.com" title="Sweet Titles">Dustin Diaz</a>.</cite>
Version: 1.1
Author: Showfom
Author URI: http://showfom.com/

**********************************************************************
Copyright (c) 2009 Showfom
Released under the terms of the GNU GPL: http://www.gnu.org/licenses/gpl.txt

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
**********************************************************************

Installation: Upload the folder "sweet-titles" with its contents to "wp-content/plugins/"  and activate the plugin in your admin panel.
*/

function SweetTitles() {
  /*  Path for snow */
	$stPath = get_option('siteurl').'/wp-content/plugins/sweet-titles/';
	$stJS .= '<!-- Generated by Sweet Titles 1.0 -->'."\n";
	$stJS .= '<script type="text/javascript" src="'.$stPath.'js/addEvent.js"></script>'."\n";
	$stJS .= '<script type="text/javascript" src="'.$stPath.'js/sweetTitles.js"></script>'."\n";
	$stJS .= '<link rel="stylesheet" href="'.$stPath.'css/sweetTitles.css" />'."\n";
	print($stJS);
}
add_action('wp_head', 'SweetTitles');
?>